name: Build and Upload Docker Image

on:
  push:
    branches:
      - master  # Adjust this branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        os: [ubuntu-20.04]
        arch: [aarch64, x86_64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker buildx create --use
        docker buildx build --platform linux/arm64,linux/amd64 -t qbittorentvpn:latest .

    - name: Save Docker image
      run: |
        mkdir -p artifacts
        docker save -o artifacts/qbittorentvpn-latest.tar qbittorentvpn:latest

  upload:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Upload to Releases
      uses: actions/upload-artifact@v3
      with:
        name: qbittorentvpn:latest
        path: artifacts/qbittorentvpn-latest.tar
